-- Improve scorecard_themes table to support Stage 4B analyzer
-- Add missing columns that the analyzer expects

-- Add missing columns for scorecard themes
ALTER TABLE scorecard_themes 
ADD COLUMN IF NOT EXISTS client_performance_summary TEXT,
ADD COLUMN IF NOT EXISTS company_list JSONB,
ADD COLUMN IF NOT EXISTS evidence_strength DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS sentiment_consistency_score DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS quote_diversity_score DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS stakeholder_weight_score DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS strategic_note TEXT,
ADD COLUMN IF NOT EXISTS competitive_positioning TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_scorecard_themes_client_id ON scorecard_themes(client_id);
CREATE INDEX IF NOT EXISTS idx_scorecard_themes_criterion ON scorecard_themes(scorecard_criterion);
CREATE INDEX IF NOT EXISTS idx_scorecard_themes_sentiment ON scorecard_themes(sentiment_direction);
CREATE INDEX IF NOT EXISTS idx_scorecard_themes_quality ON scorecard_themes(overall_quality_score DESC);

-- Add constraints for data integrity
ALTER TABLE scorecard_themes 
ALTER COLUMN client_id SET NOT NULL,
ALTER COLUMN theme_title SET NOT NULL,
ALTER COLUMN scorecard_criterion SET NOT NULL,
ALTER COLUMN sentiment_direction SET NOT NULL;

-- Add check constraints for score ranges
ALTER TABLE scorecard_themes 
ADD CONSTRAINT check_quality_score_range 
CHECK (overall_quality_score >= 0 AND overall_quality_score <= 1),
ADD CONSTRAINT check_evidence_strength_range 
CHECK (evidence_strength >= 0 AND evidence_strength <= 1),
ADD CONSTRAINT check_sentiment_consistency_range 
CHECK (sentiment_consistency_score >= 0 AND sentiment_consistency_score <= 1),
ADD CONSTRAINT check_quote_diversity_range 
CHECK (quote_diversity_score >= 0 AND quote_diversity_score <= 1),
ADD CONSTRAINT check_stakeholder_weight_range 
CHECK (stakeholder_weight_score >= 0 AND stakeholder_weight_score <= 1);

-- Add comments for documentation
COMMENT ON TABLE scorecard_themes IS 'Scorecard-driven themes generated by Stage 4B analyzer with semantic merging';
COMMENT ON COLUMN scorecard_themes.theme_title IS 'Generated theme title';
COMMENT ON COLUMN scorecard_themes.scorecard_criterion IS 'The criterion this theme relates to';
COMMENT ON COLUMN scorecard_themes.sentiment_direction IS 'Sentiment direction (positive, negative, neutral, mixed)';
COMMENT ON COLUMN scorecard_themes.client_performance_summary IS 'Summary of client performance for this criterion';
COMMENT ON COLUMN scorecard_themes.supporting_quotes IS 'JSON array of supporting quotes';
COMMENT ON COLUMN scorecard_themes.quote_count IS 'Number of supporting quotes';
COMMENT ON COLUMN scorecard_themes.companies_represented IS 'Number of companies represented';
COMMENT ON COLUMN scorecard_themes.company_list IS 'JSON array of company names';
COMMENT ON COLUMN scorecard_themes.overall_quality_score IS 'Overall quality score (0-1)';
COMMENT ON COLUMN scorecard_themes.evidence_strength IS 'Evidence strength score (0-1)';
COMMENT ON COLUMN scorecard_themes.sentiment_consistency_score IS 'Sentiment consistency score (0-1)';
COMMENT ON COLUMN scorecard_themes.quote_diversity_score IS 'Quote diversity score (0-1)';
COMMENT ON COLUMN scorecard_themes.stakeholder_weight_score IS 'Stakeholder weight score (0-1)';
COMMENT ON COLUMN scorecard_themes.strategic_note IS 'Strategic note about this theme';
COMMENT ON COLUMN scorecard_themes.competitive_positioning IS 'Competitive positioning note';
COMMENT ON COLUMN scorecard_themes.created_at IS 'Timestamp when theme was created'; 

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding columns for OpenAI (1536-dim) embeddings
ALTER TABLE core_responses ADD COLUMN IF NOT EXISTS embedding vector(1536);
ALTER TABLE scorecard_themes ADD COLUMN IF NOT EXISTS embedding vector(1536); 