# Stage 2 Analysis Configuration
# This file controls all aspects of the quote labeling and analysis process

scoring:
  # Binary + Intensity: 0 = not relevant, 1-5 = relevant with increasing importance
  scale: [0, 5]
  
  # Enhanced scoring criteria for business-relevant insights
  business_relevance_multipliers:
    specific_metrics: 1.5        # Quotes with numbers, percentages, timeframes
    competitive_comparison: 1.4   # Direct competitor mentions or comparisons
    feature_requests: 1.3         # Specific feature or capability requests
    pain_points: 1.3              # Specific problems or challenges
    success_stories: 1.2          # Positive outcomes with details
    implementation_details: 1.2   # Setup, integration, or process details
    generic_feedback: 0.8         # Reduce weight of generic statements
  
  # Deal outcome weighting factors
  deal_weighting:
    lost_deal_base: 1.2      # Lost deals get more attention
    won_deal_base: 0.9       # Won deals get less attention
    critical_multiplier: 1.5  # Amplify truly critical feedback
    minor_multiplier: 0.7     # Reduce minor feedback impact

processing:
  max_workers: 4             # Number of parallel workers
  max_quote_length: 3000     # Increased from 1000 to capture full context and nuance
  max_tokens: 8000           # Increased token limit for GPT-4o-mini
  retry_attempts: 3          # Number of retry attempts on failure
  batch_size: 50             # Batch size for processing
  model: "gpt-4o-mini"       # Upgraded from gpt-3.5-turbo-16k for better analysis
  
  # Enhanced quote filtering
  quote_filtering:
    min_specificity_score: 2.0    # Minimum score for quotes with specific details
    min_business_relevance: 2.0   # Minimum score for business-relevant quotes
    filter_generic_quotes: true   # Filter out overly generic statements
    require_concrete_details: true # Require specific examples or metrics

# Quality tracking for truncation and context preservation
quality_tracking:
  track_truncation: true     # Track when quotes are truncated
  track_context_loss: true   # Track potential context loss
  min_context_preservation: 0.8  # Minimum context preservation ratio
  truncation_warning_threshold: 0.9  # Warn when >90% of quote is used

# 10-Criteria Executive Scorecard Framework
criteria:
  product_capability:
    description: "Functionality, features, performance, and core solution fit"
    weight: 1.0
    priority_threshold: 0.8
    
  implementation_onboarding:
    description: "Deployment ease, time-to-value, setup complexity"
    weight: 1.0
    priority_threshold: 0.8
    
  integration_technical_fit:
    description: "APIs, data compatibility, technical architecture alignment"
    weight: 1.0
    priority_threshold: 0.8
    
  support_service_quality:
    description: "Post-sale support, responsiveness, expertise, SLAs"
    weight: 1.0
    priority_threshold: 0.8
    
  security_compliance:
    description: "Data protection, certifications, governance, risk management"
    weight: 1.0
    priority_threshold: 0.8
    
  market_position_reputation:
    description: "Brand trust, references, analyst recognition, market presence"
    weight: 1.0
    priority_threshold: 0.8
    
  vendor_stability:
    description: "Financial health, roadmap clarity, long-term viability"
    weight: 1.0
    priority_threshold: 0.8
    
  sales_experience_partnership:
    description: "Buying process quality, relationship building, trust"
    weight: 1.0
    priority_threshold: 0.8
    
  commercial_terms:
    description: "Price, contract flexibility, ROI, total cost of ownership"
    weight: 1.0
    priority_threshold: 0.8
    
  speed_responsiveness:
    description: "Implementation timeline, decision-making speed, agility"
    weight: 1.0
    priority_threshold: 0.8

# Stage 3: Enhanced Findings Identification Configuration
# Buried Wins v4.0 framework for executive-ready insights
stage3:
  confidence_thresholds:
    priority_finding: 2.5      # REDUCED from 3.0 for more findings
    standard_finding: 1.5      # REDUCED from 2.0 for more findings
    minimum_confidence: 0.8    # REDUCED from 1.0 for more inclusive analysis
  
  pattern_thresholds:
    minimum_quotes: 1          # REDUCED from 2 to 1 for more patterns
    minimum_companies: 1       # Keep at 1 for single-company data
    minimum_criteria_met: 1    # Keep at 1 for more inclusive analysis
    max_patterns_per_criterion: 8  # INCREASED from 5 to 8 for more patterns
  
  # Enhanced pattern recognition
  pattern_recognition:
    cross_criteria_patterns: true    # Look for patterns across multiple criteria
    semantic_similarity_threshold: 0.6  # REDUCED from 0.7 for more grouping
    business_impact_weighting: 1.5   # Weight patterns with business impact higher
    competitive_patterns: true       # Specifically look for competitive insights
    feature_request_patterns: true   # Group feature requests and enhancements
    
  stakeholder_multipliers:
    executive_perspective: 1.5      # Executive decision makers
    budget_holder_perspective: 1.5  # Budget/finance stakeholders
    champion_perspective: 1.3       # Product champions
    end_user_perspective: 1.0       # End users
    it_technical_perspective: 1.0   # Technical stakeholders
  
  decision_impact_multipliers:
    deal_tipping_point: 2.0         # Deal-breaking or deal-winning factors
    differentiator_factor: 1.5      # Competitive differentiators
    blocker_factor: 1.5             # Implementation blockers
    high_salience: 1.4              # High business impact
    medium_salience: 1.2            # Medium business impact
    low_salience: 1.0               # Low business impact
  
  evidence_strength_multipliers:
    strong_positive: 1.3            # Strong positive feedback
    strong_negative: 1.3            # Strong negative feedback
    perspective_shifting: 1.3       # Novel or unexpected insights
    organizational_conflict: 1.2    # Internal tensions or conflicts
    standard_evidence: 1.0          # Standard evidence
  
  batch_size: 100                   # Processing batch size
  max_patterns_per_criterion: 8     # INCREASED from 5 to 8 for more patterns
  max_quotes_per_finding: 4         # INCREASED from 3 to 4 for better evidence

# Stage 4: Enhanced Theme Generation Configuration
# Relaxed thresholds for human curation workflow
stage4:
  # RELAXED EVIDENCE THRESHOLDS FOR HUMAN CURATION
  min_confidence_threshold: 2.0      # REDUCED from 3.0 for human curation
  min_companies_per_theme: 2         # REDUCED from 3 to 2 for human curation
  min_findings_per_theme: 1          # REDUCED from 2 to 1 for human curation
  min_quotes_per_theme: 2            # REDUCED from 4 to 2 for human curation
  max_themes_per_category: 8         # INCREASED from 5 to 8 for more options
  
  # HIGHLY RELAXED QUALITY SCORING SYSTEM FOR HUMAN CURATION
  quality_scoring:
    specificity_threshold: 2.0       # REDUCED from 4.0 for human curation
    actionability_threshold: 1.5     # REDUCED from 3.0 for human curation
    evidence_strength_threshold: 1.5 # REDUCED from 3.0 for human curation
    min_overall_score: 2.0          # REDUCED from 3.5 for human curation
  
  # QUOTE DEDUPLICATION
  quote_deduplication:
    enabled: true
    similarity_threshold: 0.8        # Prevent quotes with >80% similarity
    max_quote_reuse: 1               # Maximum times a quote can be used
  
  # FUZZY MATCHING IMPROVEMENTS
  fuzzy_matching:
    similarity_threshold: 0.7        # REDUCED from 0.75 for more inclusive grouping
    semantic_grouping: true
    cross_criteria_grouping: true
    min_group_size: 2                # REDUCED from 3 to 2 for human curation
  
  # THEME CATEGORIES
  theme_categories:
    product_features: "Specific product capabilities and features"
    customer_pain_points: "Concrete customer issues and challenges"
    competitive_advantages: "Measurable competitive benefits"
    market_opportunities: "Actionable market insights"
    implementation_barriers: "Specific implementation challenges"
    strategic_insights: "High-level strategic implications"
  
  # COMPETITIVE DETECTION
  competitive_keywords: [
    'vs', 'versus', 'compared to', 'alternative', 'competitor',
    'switching', 'migration', 'evaluation', 'selection process',
    'vendor', 'solution', 'platform', 'tool', 'competition',
    'market leader', 'industry standard', 'best in class'
  ]

# Quality control settings
quality:
  min_confidence: "medium"   # Minimum confidence level to include in analysis
  max_processing_errors: 10  # Maximum errors before stopping processing 