# Stage 2 Analysis Configuration
# This file controls all aspects of the quote labeling and analysis process

scoring:
  # Binary + Intensity: 0 = not relevant, 1-5 = relevant with increasing importance
  scale: [0, 5]
  
  # Deal outcome weighting factors
  deal_weighting:
    lost_deal_base: 1.2      # Lost deals get more attention
    won_deal_base: 0.9       # Won deals get less attention
    critical_multiplier: 1.5  # Amplify truly critical feedback
    minor_multiplier: 0.7     # Reduce minor feedback impact

processing:
  max_workers: 4             # Number of parallel workers
  max_quote_length: 1000     # Maximum characters to send to LLM
  retry_attempts: 3          # Number of retry attempts on failure
  batch_size: 50             # Batch size for processing

# 10-Criteria Executive Scorecard Framework
criteria:
  product_capability:
    description: "Functionality, features, performance, and core solution fit"
    weight: 1.0
    priority_threshold: 0.8
    
  implementation_onboarding:
    description: "Deployment ease, time-to-value, setup complexity"
    weight: 1.0
    priority_threshold: 0.8
    
  integration_technical_fit:
    description: "APIs, data compatibility, technical architecture alignment"
    weight: 1.0
    priority_threshold: 0.8
    
  support_service_quality:
    description: "Post-sale support, responsiveness, expertise, SLAs"
    weight: 1.0
    priority_threshold: 0.8
    
  security_compliance:
    description: "Data protection, certifications, governance, risk management"
    weight: 1.0
    priority_threshold: 0.8
    
  market_position_reputation:
    description: "Brand trust, references, analyst recognition, market presence"
    weight: 1.0
    priority_threshold: 0.8
    
  vendor_stability:
    description: "Financial health, roadmap clarity, long-term viability"
    weight: 1.0
    priority_threshold: 0.8
    
  sales_experience_partnership:
    description: "Buying process quality, relationship building, trust"
    weight: 1.0
    priority_threshold: 0.8
    
  commercial_terms:
    description: "Price, contract flexibility, ROI, total cost of ownership"
    weight: 1.0
    priority_threshold: 0.8
    
  speed_responsiveness:
    description: "Implementation timeline, decision-making speed, agility"
    weight: 1.0
    priority_threshold: 0.8

# Stage 3: Enhanced Findings Identification Configuration
# Buried Wins v4.0 framework for executive-ready insights
stage3:
  confidence_thresholds:
    priority_finding: 3.0      # Reduced from 4.0 for more inclusive analysis
    standard_finding: 2.0      # Reduced from 3.0 for more inclusive analysis
    minimum_confidence: 1.0    # Reduced from 2.0 for more inclusive analysis
  
  pattern_thresholds:
    minimum_quotes: 2          # Reduced from 3 to 2 for smaller datasets
    minimum_companies: 1       # Reduced from 2 to 1 for single-company data
    minimum_criteria_met: 1    # Reduced from 2 to 1 for more inclusive analysis
  
  stakeholder_multipliers:
    executive_perspective: 1.5      # Executive decision makers
    budget_holder_perspective: 1.5  # Budget/finance stakeholders
    champion_perspective: 1.3       # Product champions
    end_user_perspective: 1.0       # End users
    it_technical_perspective: 1.0   # Technical stakeholders
  
  decision_impact_multipliers:
    deal_tipping_point: 2.0         # Deal-breaking or deal-winning factors
    differentiator_factor: 1.5      # Competitive differentiators
    blocker_factor: 1.5             # Implementation blockers
    high_salience: 1.4              # High business impact
    medium_salience: 1.2            # Medium business impact
    low_salience: 1.0               # Low business impact
  
  evidence_strength_multipliers:
    strong_positive: 1.3            # Strong positive feedback
    strong_negative: 1.3            # Strong negative feedback
    perspective_shifting: 1.3       # Novel or unexpected insights
    organizational_conflict: 1.2    # Internal tensions or conflicts
    standard_evidence: 1.0          # Standard evidence
  
  batch_size: 100                   # Processing batch size
  max_patterns_per_criterion: 5     # Maximum patterns per criterion
  max_quotes_per_finding: 3         # Maximum quotes per finding

# Quality control settings
quality:
  min_confidence: "medium"   # Minimum confidence level to include in analysis
  max_processing_errors: 10  # Maximum errors before stopping processing 